[build]
  publish = "publish/wwwroot"
  command = "dotnet publish TshirtMaker/TshirtMaker.csproj -c Release -o publish /p:TreatWarningsAsErrors=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200