[build]
  publish = "TshirtMaker/bin/Release/net8.0/browser-wasm/publish/wwwroot"
  command = "dotnet publish TshirtMaker/TshirtMaker.csproj -c Release -p:TreatWarningsAsErrors=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  DOTNET_VERSION = "8.0.203"
  # REMOVE NODE_VERSION - .NET doesn't need it